In [20]:
import numpy as np
import pandas as pd
from pandas import DataFrame
import scipy as sp
import string
import json
import re
import sklearn.metrics as metrics
from sklearn.feature_extraction.text import CountVectorizer
import matplotlib.pyplot as  plt
import seaborn as sns
import sklearn
from sklearn.metrics import accuracy_score
####

from sklearn.model_selection import train_test_split
from sklearn import linear_model
import statsmodels.api as sm

from sklearn.linear_model import LogisticRegression
import sklearn.linear_model as linear_model
import sklearn.model_selection as model_selection

from sklearn import svm
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier

In [2]:
# open training dataset and parse recipes

with open('train.json') as cooking_file:  
    
    data = json.load(cooking_file)
    

In [3]:
#removing punctuations and spaces before fixing the data and keep them all in a dict  (italian, mexican)

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

def gather_recipes(recipes, cuisine_country):
    
    data_list = []
    
    for _object in recipes:
        
        if _object.get('cuisine') == cuisine_country:
            
            ingredients = _object.get('ingredients') 
            _id = _object.get('id')
            
            for i in ingredients:
                
                _dict = dict()
                ingr = i.replace(' ', '').lower()
                    
                for ch in ingr: 
                    
                    if ch in punctuations: 
                        
                        ingr = ingr.replace(ch, '')  
                
                _dict['ingredients'] = ingr                
                _dict['id'] = _id
                data_list.append(_dict)
                
    return data_list

clean_italian_cuisine_data = gather_recipes(data, 'italian')
clean_mexican_cuisine_data = gather_recipes(data, 'mexican')

In [4]:
#creating dfs  (italian, mexican)

italian_df = DataFrame(clean_italian_cuisine_data)
italian_ingredients = list(set(italian_df.ingredients))

mexican_df = DataFrame(clean_mexican_cuisine_data)
mexican_ingredients = list(set(mexican_df.ingredients))


In [5]:
#fixing data for CountVectorizer (italian_df)

it_unique_ids = []
it_ingredients = []
it_grouped = italian_df.groupby('id')

for ids, ing in it_grouped:
    
    it_unique_ids.append(ids)
    
    row = str(ing)
    row = row.replace('ingredients','')
    row = row.replace('id', '')
    row = row.replace('\n', '')
    row = re.sub('[0-9]+', '', row)
    row = row.split( )
    row = ' '.join(row)
    
    it_ingredients.append(row)
    

In [6]:
#fixing data for CountVectorizer (mexican_df)

mex_unique_ids = []
mex_ingredients = []
mex_grouped = mexican_df.groupby('id')

for ids, ing in mex_grouped:
    
    mex_unique_ids.append(ids)
    
    row = str(ing)
    row = row.replace('ingredients','')
    row = row.replace('id', '')
    row = row.replace('\n', '')
    row = re.sub('[0-9]+', '', row)
    row = row.split( )
    row = ' '.join(row)
    
    mex_ingredients.append(row)
    


In [7]:
#using CountVectorizer  (italian, mexican) and adding one column Cuisine

it_vectorizer = CountVectorizer(analyzer = 'word', binary = True)
it_array = it_vectorizer.fit_transform(it_ingredients)
it_array = it_array.toarray()

it_df = DataFrame(it_array, columns = it_vectorizer.get_feature_names(), index = it_unique_ids)
it_df['Cuisine'] = 0 #italian
it_df.to_csv('it_cleandata.csv', index_label = 'ID')
print(it_df)

mex_vectorizer = CountVectorizer(analyzer = 'word', binary = True)
mex_array = mex_vectorizer.fit_transform(mex_ingredients)
mex_array = mex_array.toarray()

mex_df = DataFrame(mex_array, columns = mex_vectorizer.get_feature_names(), index = mex_unique_ids)
mex_df['Cuisine'] = 1 #mexican
mex_df.to_csv('mex_cleandata.csv', index_label = 'ID')
print(mex_df)

       abbamele  accent  acinipepe  acornsquash  activedryyeast  adobosauce  \
4             0       0          0            0               0           0   
14            0       0          0            0               0           0   
20            0       0          0            0               0           0   
56            0       0          0            0               0           0   
62            0       0          0            0               0           0   
...         ...     ...        ...          ...             ...         ...   
49679         0       0          0            0               0           0   
49681         0       0          0            0               0           0   
49689         0       0          0            0               0           0   
49697         0       0          0            0               0           0   
49708         0       0          0            0               0           0   

       adoboseasoning  agavenectar  agedbalsamicvin

In [8]:
#putting mexican and italian in one DataFrame

df = pd.DataFrame(it_df)
df = df.append(mex_df, sort = False)
df.fillna(0, inplace = True)
df = df.astype('int64')
print(df['Cuisine'])

4        0
14       0
20       0
56       0
62       0
        ..
49678    1
49687    1
49707    1
49709    1
49717    1
Name: Cuisine, Length: 14276, dtype: int64


In [9]:
X = df.loc[:, df.columns != 'Cuisine'].values  #all columns with values except Cuisine column
print(X)
print(X.shape)

Y = df['Cuisine'] #just the ids in a list
#print(Y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(14276, 3976)


In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [11]:
# Multiple Logistic Regression 

lr_m = linear_model.LogisticRegression()
lr_m.fit(X_train, Y_train)

In [12]:
print("classifier score:",lr_m.score(X_test, Y_test))
Y_pred = lr_m.predict(X_test)
print("\naccuracy:",metrics.accuracy_score(Y_test, Y_pred))
print("\nConfusion matrix:")
print(metrics.confusion_matrix(Y_test, Y_pred))
print("\nPrecision Score per class:")
print(metrics.precision_score(Y_test, Y_pred, average = None))
print("\nAverage Precision Score:")
print(metrics.precision_score(Y_test, Y_pred, average = 'weighted'))
print("\nRecall Score per class:")
print(metrics.recall_score(Y_test, Y_pred, average = None))
print("\nAverage Recall Score:")
print(metrics.recall_score(Y_test, Y_pred, average = 'weighted'))
print("\nF1-score Score per class:")
print(metrics.f1_score(Y_test, Y_pred, average = None))
print("\nAverage F1 Score:")
print(metrics.f1_score(Y_test, Y_pred, average = 'weighted'))

report = metrics.classification_report(Y_test,Y_pred)
print(report)

classifier score: 0.9686186606892687

accuracy: 0.9686186606892687

Confusion matrix:
[[1887   40]
 [  72 1570]]

Precision Score per class:
[0.96324655 0.97515528]

Average Precision Score:
0.9687254354733641

Recall Score per class:
[0.97924235 0.95615104]

Average Recall Score:
0.9686186606892687

F1-score Score per class:
[0.97117859 0.96555966]

Average F1 Score:
0.9685934707348253


In [13]:
scores = model_selection.cross_val_score(lr_m, X, Y, scoring = 'f1_weighted', cv = 5)
print('scores:', scores)
print('mean scores:', scores.mean())

scores: [0.96809087 0.97195581 0.96879183 0.96668815 0.96880957]
mean scores: 0.9688672451742961


In [14]:
#scores = model_selection.cross_val_score(#lr_m,
                                          #svm_m,
                                          #knn,
                                          #dtree,
                                          #X,
                                          #Y,
                                          #scoring='f1_weighted',
                                          #cv=5)
#print (scores)
#print (scores.mean())

In [15]:
# Support Vector Machines

svm_m = svm.SVC()
svm_m.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [16]:
print("classifier score:",svm_m.score(X_test, Y_test))
Y_pred = svm_m.predict(X_test)
print("\naccuracy:",metrics.accuracy_score(Y_test, Y_pred))
print("\nConfusion matrix:")
print(metrics.confusion_matrix(Y_test, Y_pred))
print("\nPrecision Score per class:")
print(metrics.precision_score(Y_test, Y_pred, average = None))
print("\nAverage Precision Score:")
print(metrics.precision_score(Y_test, Y_pred, average = 'weighted'))
print("\nRecall Score per class:")
print(metrics.recall_score(Y_test, Y_pred, average= None))
print("\nAverage Recall Score:")
print(metrics.recall_score(Y_test, Y_pred, average = 'weighted'))
print("\nF1-score Score per class:")
print(metrics.f1_score(Y_test, Y_pred, average = None))
print("\nAverage F1 Score:")
print(metrics.f1_score(Y_test, Y_pred, average = 'weighted'))

report = metrics.classification_report(Y_test,Y_pred)
print(report)

classifier score: 0.9649761838049874

accuracy: 0.9649761838049874

Confusion matrix:
[[1894   33]
 [  92 1550]]

Precision Score per class:
[0.95367573 0.97915351]

Average Precision Score:
0.9653973630645947

Recall Score per class:
[0.98287494 0.94397077]

Average Recall Score:
0.9649761838049874

F1-score Score per class:
[0.9680552  0.96124031]

Average F1 Score:
0.9649198545052377


In [18]:
#Decision Trees

dtree = tree.DecisionTreeClassifier()
dtree = dtree.fit(X_train, Y_train)

print("classifier accuracy:",dtree.score(X_test, Y_test))

Y_pred = dtree.predict(X_test)
Y_prob = dtree.predict_proba(X_test)
print("classifier predictions:", Y_pred)
print("ground truth labels   :", Y_test)
print(Y_prob)

classifier accuracy: 0.9366769403194172
classifier predictions: [1 0 0 ... 1 0 1]
ground truth labels   : 41913    1
39513    0
31187    0
47868    1
26047    0
        ..
21426    0
16747    0
37271    1
13967    0
7027     1
Name: Cuisine, Length: 3569, dtype: int64
[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]


In [19]:
print("accuracy:", metrics.accuracy_score(Y_test, Y_pred))
print("\nConfusion matrix:")
print(metrics.confusion_matrix(Y_test, Y_pred))
print("\nPrecision Score per class:")
print(metrics.precision_score(Y_test, Y_pred, average=None))
print("\nAverage Precision Score:")
print(metrics.precision_score(Y_test, Y_pred, average='weighted'))
print("\nRecall Score per class:")
print(metrics.recall_score(Y_test, Y_pred, average=None))
print("\nAverage Recall Score:")
print(metrics.recall_score(Y_test, Y_pred, average='weighted'))
print("\nF1-score Score per class:")
print(metrics.f1_score(Y_test, Y_pred, average=None))
print("\nAverage F1 Score:")
print(metrics.f1_score(Y_test, Y_pred, average='weighted'))

report = metrics.classification_report(Y_test,Y_pred)
print(report)

accuracy: 0.9366769403194172

Confusion matrix:
[[1816  111]
 [ 115 1527]]

Precision Score per class:
[0.94044537 0.93223443]

Average Precision Score:
0.9366677378169107

Recall Score per class:
[0.94239751 0.92996346]

Average Recall Score:
0.9366769403194172

F1-score Score per class:
[0.94142043 0.93109756]

Average F1 Score:
0.9366711555818912


In [29]:
#k-NN

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [30]:
print("classifier score:", knn.score(X_test, Y_test))

Y_pred = knn.predict(X_test)

print("\naccuracy:",metrics.accuracy_score(Y_test, Y_pred))
print("\nConfusion matrix:")
print(metrics.confusion_matrix(Y_test, Y_pred))
print("\nPrecision Score per class:")
print(metrics.precision_score(Y_test, Y_pred, average = None))
print("\nAverage Precision Score:")
print(metrics.precision_score(Y_test, Y_pred, average = 'weighted'))
print("\nRecall Score per class:")
print(metrics.recall_score(Y_test, Y_pred, average = None))
print("\nAverage Recall Score:")
print(metrics.recall_score(Y_test, Y_pred, average = 'weighted'))
print("\nF1-score Score per class:")
print(metrics.f1_score(Y_test, Y_pred, average = None))
print("\nAverage F1 Score:")
print(metrics.f1_score(Y_test, Y_pred, average = 'weighted'))

report = metrics.classification_report(Y_test,Y_pred)
print('Report:', report)

classifier score: 0.8391706360325021

accuracy: 0.8391706360325021

Confusion matrix:
[[1858   69]
 [ 505 1137]]

Precision Score per class:
[0.78628862 0.94278607]

Average Precision Score:
0.8582888455365175

Recall Score per class:
[0.96419305 0.69244823]

Average Recall Score:
0.8391706360325021

F1-score Score per class:
[0.86620047 0.79845506]

Average F1 Score:
0.8350326423691481
Report:               precision    recall  f1-score   support

           0       0.79      0.96      0.87      1927
           1       0.94      0.69      0.80      1642

    accuracy                           0.84      3569
   macro avg       0.86      0.83      0.83      3569
weighted avg       0.86      0.84      0.84      3569

